### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by m0iises19** [d4xn/esx_euromillon_d4xn#1]
he won't let you buy the ticket

**Comment by m0iises19** [comment]
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`, `price`, `weight`) VALUES
	('boleto_euromillon', 'Boleto Euromillon', -1, 0, 1, 12, 1)
;

sql for extended 1-final wrong

extended 1-final:
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES

**Comment by d4xn** [comment]
Okey thanks! What should I do? Change the file EUROMILLON.sql and add INSERT INTO items (name, label, weight, rare, can_remove) VALUES ? Anyway it works well for me, but if you have any problem contact with me!

**Comment by m0iises19** [comment]
not right, the npc does not sell you the tickets, you have put the prices in a table of "items"

**Comment by d4xn** [comment]
> not right, the npc does not sell you the tickets, you have put the prices in a table of "items"

I have put the price in the table items, but it is useless, because the purchase is made from the script, it takes away 12 dollars and gives you a ticket.
And if you dont have 12$ or more, the script shows an alert at the bottom left of the screen.

**Comment by m0iises19** [comment]
the npc does nothing, does not take your money or give you tickets.

It also doesn't show any alerts.

**Comment by d4xn** [comment]
> the npc does nothing, does not take your money or give you tickets.
> 
> It also doesn't show any alerts.

To me, works perfectly.
Did you get any error in the console? Check that you have followed all the steps in README.md

**Comment by m0iises19** [comment]
I do not receive any error in console, I will try it again and I will comment

**Comment by d4xn** [comment]
> I do not receive any error in console, I will try it again and I will comment

I think I have an error in the code, let me check it!

**Comment by d4xn** [comment]
Bro sorry!!!! You have to change line 26 in client.lua
```lua
                TriggerServerEvent('esx_euromillon_d4xn:darBoletos_d4xn')
```

**Comment by m0iises19** [comment]
Anyway, you have put the price in the table of "items", it is impossible for the NPC to charge you the 12 $ when talking to him, since for extended 1-final the table has to be like this:

extended 1-final:
INSERT INTO items (name, label, weight, rare, can_remove) VALUES

**Comment by d4xn** [comment]
> Anyway, you have put the price in the table of "items", it is impossible for the NPC to charge you the 12 $ when talking to him, since for extended 1-final the table has to be like this:
> 
> extended 1-final:
> INSERT INTO items (name, label, weight, rare, can_remove) VALUES

So I change EUROMILLON.sql ? 
```sql
INSERT INTO items (name, label, weight, rare, can_remove) VALUES
	('boleto_euromillon', 'Boleto Euromillon', 1, 0, 1)
;
```
Now it's okey??
Thanks!!

**Comment by m0iises19** [comment]
ok now yes. Now my question is, when is the ticket played?

Isn't it better if it is played automatically every x time?

**Comment by d4xn** [comment]
> ok now yes. Now my question is, when is the ticket played?
> 
> Isn't it better if it is played automatically every x time?

It's a good idea, It's easy to do, later I'll look at it to see what I do

**Comment by m0iises19** [comment]
Do you speak Spanish?

**Comment by d4xn** [comment]
> Do you speak Spanish?

Yes

**Comment by m0iises19** [comment]
pues estaria bien que al comprar el boleto, se juegue cada x tiempo, ya que le da mas realismo y jugaria mas gente a la vez.

Aparte aun que tu tengas el inventario lleno de peso, el npc te sigue vendiendo boletos sin importarle que en tu inventario no puedas llevar mas cosas por el peso.

**Comment by d4xn** [comment]
> pues estaria bien que al comprar el boleto, se juegue cada x tiempo, ya que le da mas realismo y jugaria mas gente a la vez.
> 
> Aparte aun que tu tengas el inventario lleno de peso, el npc te sigue vendiendo boletos sin importarle que en tu inventario no puedas llevar mas cosas por el peso.

Entiendo lo que quieres decir, de hecho es muy buena idea no lo había pensado, en cuanto pueda me pondré a desarrollarlo. Gracias!! Voy a cerrar la issue pero si quieres contactarme puedes hacerlo por discord $DaNx#1402
